import requests, sys, re, time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By


# driver = r"/usr/local/bin/geckodriver"

# browser = webdriver.Firefox(executable_path=driver)
# wait = WebDriverWait(browser, 120)


# words = "./data/params/workable.txt"
# www = r"https://apply.workable.com/(.*?)/"
# link = "https://apply.workable.com"


# words = "./data/params/greenhouse_io.txt"
# www = r"https://boards.greenhouse.io/(.*?)/"
# link = "https://boards.greenhouse.io"


# words = "./data/params/lever_co.txt"
# www = r"https://jobs.lever.co/(.*?)/"
# link = "https://jobs.lever.co"

# words = "./data/params/smartrecruiters.txt"
# www = r"https://careers.smartrecruiters.com/(.*?)/"
# link = "https://careers.smartrecruiters.com"

# words = "./data/params/ashbyhq.txt"
# www = r"https://jobs.ashbyhq.com/(.*?)/"
# link = "https://jobs.ashbyhq.com"

# words = "./data/params/jazzhr.txt"
# www = r"https://(.*?).applytojob.com/"
# link = "https://jobs.ashbyhq.com"

# words = "./data/params/breezyhr.txt"
# www = r"https://(.*?).breezy.hr/"
# link = "https://jobs.ashbyhq.com"

words = "./data/params/jobvite.txt"
www = r"https://jobs.jobvite.com/careers/(.*?)/"
# link = "https://jobs.ashbyhq.com"


f = open(words, "r")
text = [company.lower().strip() for company in f]
f.close()


duck = [
'http://jobs.jobvite.com/careers/ashoka/',
'http://jobs.jobvite.com/careers/blackline/',
'http://jobs.jobvite.com/careers/on24//',
'https://jobs.jobvite.com/careers/loandepot//',
'http://jobs.jobvite.com/careers/align//',
'http://jobs.jobvite.com/careers/earthjustice/',
'http://jobs.jobvite.com/careers/hylant//',
'http://jobs.jobvite.com/careers/aak//',
'http://jobs.jobvite.com/careers/apco/',
'http://jobs.jobvite.com/careers/nakisa//',
'http://jobs.jobvite.com/careers/avetta/',
'https://jobs.jobvite.com/careers/360care/jobs?error=301/',
'http://jobs.jobvite.com/careers/pathoras//',
'https://jobs.jobvite.com/careers/joinreal/',
'http://jobs.jobvite.com/careers/meijer/',
'http://jobs.jobvite.com/careers/rhapsody//',
'http://jobs.jobvite.com/careers/groupm-china//',
'https://jobs.jobvite.com/careers/cscareers/jobs/',
'http://jobs.jobvite.com/careers/itw-internal//',
'http://jobs.jobvite.com/careers/mindshare/jobs/',
'http://jobs.jobvite.com/careers/hwc/jobs/',
'http://jobs.jobvite.com/careers/hornall-anderson//',
'https://jobs.jobvite.com/careers/citco/job/oxAcgfwj/',
'https://jobs.jobvite.com/careers/wc-executives/job/',
'https://jobs.jobvite.com/careers/western-growers-association//',
'https://jobs.jobvite.com/careers/splunk/job/os9Uffwu/',
'https://jobs.jobvite.com/careers/mercycorps/job/oiMDgfwH/',
'https://jobs.jobvite.com/careers/dhr-rgv/jobs/',
'http://jobs.jobvite.com/careers/pt-holdings/jobs/',
'https://jobs.jobvite.com/careers/ncu/job/o2sfgfwJ/',
'https://jobs.jobvite.com/careers/sermo/job/o8kzgfw1/',
'https://jobs.jobvite.com/careers/xlconstruction/job/ooEdffwe/',
'https://jobs.jobvite.com/careers/brafton/job/olhPefwp/',
'https://jobs.jobvite.com/careers/vmlyr/job/olSoffwA/',
'https://jobs.jobvite.com/careers/newrelic/job/ooXwgfwR/',
'http://jobs.jobvite.com/careers/crystal-dynamics/jobozNKdfw3/',
'http://jobs.jobvite.com/careers/centralway/jobs/',
'https://jobs.jobvite.com/careers/innio/job/oxWngfwQ/',
'https://jobs.jobvite.com/careers/torrid/job/ojjO8fwi?/',
'http://jobs.jobvite.com/careers/nmr-consulting/jobs/',
'https://jobs.jobvite.com/careers/victaulic/job/oEDSffw8?__jvst=Job%20Board&__jvsd=Indeed/',
'https://jobs.jobvite.com/careers/actionet/jobs?error=301/',
'https://jobs.jobvite.com/careers/pac-12-networks/jobs/',
'https://jobs.jobvite.com/careers/innio/jobs?error=404/',
'https://jobs.jobvite.com/careers/lazboysouthernontario/jobs?error=301/',
'https://jobs.jobvite.com/careers/knowles/jobs?error=301/',
'https://jobs.jobvite.com/careers/logitech/jobs?error=404/',
'https://jobs.jobvite.com/careers/baylismedical/jobs?error=404/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oW2JdfwE/abc/',
'https://jobs.jobvite.com/careers/sage-intacct/job/otpngfwf/',
'https://jobs.jobvite.com/careers/aak/jobs?error=404/',
'https://jobs.jobvite.com/careers/citco/jobs?error=404/',
'http://jobs.jobvite.com/careers/smarsh/jobs?error=404/',
'https://jobs.jobvite.com/careers/torrid/job/ogrO8fwn?utm_/',
'https://jobs.jobvite.com/careers/neogenomics/jobs?error=301/',
'https://jobs.jobvite.com/careers/abt/jobs?error=301/',
'https://jobs.jobvite.com/careers/shutterfly/jobs?error=301/',
'http://jobs.jobvite.com/careers/prodege/jobs?__jvst=Career/',
'https://jobs.jobvite.com/careers/sage-intacct/job/oz9kffw1/',
'https://jobs.jobvite.com/careers/thiqah/job/ozXLgfwh/',
'http://jobs.jobvite.com/careers/odyssey-reinsurance-company/jobs/',
'https://jobs.jobvite.com/careers/sage-intacct/job/oAbpgfwa/',
'https://jobs.jobvite.com/careers/torrid/job/oesO8fwm?utm_/',
'http://jobs.jobvite.com/careers/systempavers/jobs?error=404/',
'https://jobs.jobvite.com/careers/siriusxm/job/oWh9gfwm?__jvst/',
'https://jobs.jobvite.com/careers/bistatedev/jobs?error=404/',
'http://jobs.jobvite.com/careers/bkf/jobs?error=404/',
'https://jobs.jobvite.com/careers/newyork-public-radio/job/oIOwgfw2/',
'http://jobs.jobvite.com/careers/sega-europe-limited/job/o8o1ffww/',
'http://jobs.jobvite.com/careers/worldclassexecutives/jobs?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/incontact/jobs?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/sega-europe-limited/job/omTtgfwI/',
'https://jobs.jobvite.com/careers/dentwizard/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/blackline/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/epizyme/jobs?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/herbalifepl/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/isg-one/jobs?error=301/',
'https://jobs.jobvite.com/careers/groupm-emea/jobs?error=301/',
'https://jobs.jobvite.com/careers/groupm-apac/jobs?error=404/',
'https://jobs.jobvite.com/careers/freedomfinancialnetwork/job/oW2egfwc?jobfairsin.com/',
'http://jobs.jobvite.com/careers/lewispr/jobs?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/sega-europe-limited/job/owWDgfw5/',
'http://jobs.jobvite.com/careers/themergermarketgroup/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/resolver/jobs?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/sega-europe-limited/job/oggPffwk/',
'http://jobs.jobvite.com/careers/rexfordindustrial/jobs?error=404/',
'http://jobs.jobvite.com/careers/herbalifeuk/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/nbbj/job/okOPafwR?s=ziprecruiter/',
'http://jobs.jobvite.com/careers/apcera/jobs?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/kbs/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/livevision/jobs?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/oGyzgfwN?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o7Xdgfwh?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oL1bgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oH5egfw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/texashealthrockwall/jobs?__jvst=Career%20Site/',
'https://jobs.jobvite.com/careers/gpc/job/o2Xcgfwb?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oa1GgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o5U9gfw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/siriusxm/job/osPOffw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/odTyffwD?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oLaKgfwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/mediacom/job/otEGffwM?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oOUsgfwa?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tivo/jobs?error=404&nl=1/',
'https://jobs.jobvite.com/careers/rightpoint/job/oUFFffwd?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oJkrgfwu?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kwalee/job/oUTQefwB?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oyR8ffww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/hkstrategies/job/o9nSffwn?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/ojdKffwf?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/oydvffwf?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/oNVzffwg?__jvst=job+board/',
'https://jobs.jobvite.com/careers/atirestoration/job/onX5efwn?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/oiO4efw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/opObgfwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oKsXffw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/atirestoration/job/oQnWdfw6?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/owfEgfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oBebgfw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/edobest/job/opgoffw2?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/rightpoint/job/oZWTdfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/lazparking/job/o99bgfwt?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oQmgffwr?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oYfFgfwS?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oieQffwl?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/ouHEgfwP?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oo6Fffw8?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/o0a4ffwd?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/von/job/osMIffwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gatewaycasinos/job/ojjwgfw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/imprivata/jobs?error=404&nl=1/',
'https://jobs.jobvite.com/careers/splunk/job/o3GGffwo?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/citco/job/oOAKffw7?__jvst=job+board&/',
'https://jobs.jobvite.com/careers/rightpoint/job/oCoygfwy?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/oKAnffwG?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/trustwave/job/okU3ffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/ojfuffw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/splunk/job/okLLffwP?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oBMkffwG?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/guidepoint-security/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/baymark/job/oJ1gffwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/yodlee/job/oJAEgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/xylem/job/ocSTffwW?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/biomarin/job/o2WUffwR?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oqLlgfww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/infoblox/job/ouvTffwR?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/siriusxm/job/os4Sefwm?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/o9Nagfw6?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/splunk/job/o19HffwQ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/ouGCffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/baymark/job/oawgffwV?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/siriusxm/job/o7a8ffwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/yodlee/job/osKdgfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oXUygfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/o6Sbffw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/martinmarietta/job/odAFgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oePzgfwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/biomarin/job/obHRffwI?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/okMzgfwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oxTzffwY?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o8olgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oVZSffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dotdash/job/o5Vfffwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oo8lgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oT8rgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oge7efwz?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/yodlee/job/oONjgfwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o3ZFgfwH?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o4Wuffwt?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/fieldcore/job/onoHffwr?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/mediacom/job/oEJPefwa?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oQzFgfw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/wavemaker/job/ovUCefwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/oh6mgfwJ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/aspirepublicschools/job/oEwKffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/oZbKffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/oC22efwE?__jvst=job+board/',
'https://jobs.jobvite.com/careers/aspirepublicschools/job/otysffws?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/miniclip/job/o1zygfw8?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/o8yfgfwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/ouFBffwJ?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/oSlEffwQ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/macallistermachinery/job/oncHffwf?__jvst=career+site/',
'https://jobs.jobvite.com/careers/chevo-consulting/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oC9WffwG?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oCk0ffwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/omqIefws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oxB7efwd?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/o3x3ffwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/lewispr/job/oG2Cgfwk?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oZLygfwi?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/info-stretch-corporation/job/oqrigfw9/',
'https://jobs.jobvite.com/careers/yodlee/job/oQ4Egfwy?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/owo8ffw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oMu9gfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/biomarin/job/oQI0cfwu?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/cmpa/job/oEAxgfwL?__jvst=Job+Board/',
'http://jobs.jobvite.com/careers/rlb/jobs?__jvst=RLB%20Website/',
'https://jobs.jobvite.com/careers/kathmandu/job/olokffw2?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/o2frgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oCTOefwh?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/oDvkgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/obKggfwb?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/o8kmffwN?__jvst=job+board/',
'https://jobs.jobvite.com/careers/rightpoint/job/ok1wgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oqLxgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oqhO8fwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oS8VffwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dentwizard/job/om2zgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oaP1ffwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oLhugfww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oiXVffw9?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/siriusxm/job/oPLxgfw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oM9ZffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o8zUffwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oQ9ygfwx?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qlik/job/oBRBffw2?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/trustwave/job/opZPffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/seco-energy/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/enterey/job/oJFKgfw8?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oqoDgfwr?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rtbhouse/job/oaaYefwg?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oryBgfwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/incontact/job/ofgoffwS?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/oBXxffw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oPPPffws?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/wavemaker/job/osl1efwM?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/dealcloud/jobs?__jvst=Intapp+Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oytrefwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oU4wgfwu?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/pilgrims/job/ouyPffwQ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/biomarin/job/oW3BgfwA?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/tngretail/job/of2egfwv?__jvst=career+site/',
'https://jobs.jobvite.com/careers/salsa/job/onaIgfwf?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/o9Qbgfwa?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/opVAgfwU?__jvst=job+board/',
'https://jobs.jobvite.com/careers/torrid/job/ofEX8fwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oNn5ffwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/oxtpffwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/internetbrands/job/otDbffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/atirestoration/job/oAQfffwE?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/pitchbook/job/oOlxffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/o0ivgfwN?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/o6Kxgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oF1Sffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/tivo/job/onBmffwj?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oxgeffw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/infoblox/job/ox0sgfwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/ol4kgfwJ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tivo/job/o8SGffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/hkstrategies/job/o4J2ffwO?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/kathmandu/job/onZAgfwW?__jvst=job+board/',
'https://jobs.jobvite.com/careers/qualys/job/oGqFgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/oJ6qffwe?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/oFdKgfwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/perrigocareers/job/ojP5ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/ovsPffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/customink/job/oO6ngfwh?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/service/redirect?c=qqq9VfwE&k=Jobs&j=o4kj4fwv&__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oqMcffwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oO80ffwV?__jvst=career+site/',
'https://jobs.jobvite.com/careers/ccaglobalpartners/job/ol3tgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/opzqgfwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/chiefind/job/oCSPffwi?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/oqabgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/o3vO8fwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/von/job/o7v2ffwD?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/benihana/job/osgFgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/oqEmffwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/centurycommunities/job/oiADgfwv?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oLRNffwo?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/omoO8fwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oCL0ffwm?__jvst=career+site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oHtOffwX?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/torrid/job/ofYP8fwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/ohFCffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/canadacartage/job/oAXXffwt?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/nakisa/job/oA0Pffwo?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/argusmedia/job/oVtEffw1?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/obArgfwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/macapartments/jobs?__jvst=JobBoard&__jvsd=Indeed/',
'https://jobs.jobvite.com/careers/benefitfocus/job/oxwXffwZ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/sbmmanagement/job/omMEgfwM?__jvst=career+site/',
'https://jobs.jobvite.com/careers/rehmann/job/ozB7ffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/shutterfly/job/oRDkdfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/herbalifenl/jobs?__jvst=Career%20Site/',
'https://jobs.jobvite.com/careers/hhglobal/job/opLBffwK?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/olhpgfw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oARO8fw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qualys/job/oTd7ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oTPlgfw3?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/oJqO8fwP?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=404/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=301/',
'https://jobs.jobvite.com/careers/carfax/p/main/',
'https://jobs.jobvite.com/careers/wri/jobs?error=301/',
'https://jobs.jobvite.com/careers/wilsonart/jobs?error=404/',
'https://jobs.jobvite.com/careers/cnoinc/jobs?error=301/',
'https://jobs.jobvite.com/careers/evergreenhealth/jobs?error=301/',
'https://jobs.jobvite.com/careers/panasonic/job/odTyffwD?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oLaKgfwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/mediacom/job/otEGffwM?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oOUsgfwa?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tivo/jobs?error=404&nl=1/',
'https://jobs.jobvite.com/careers/rightpoint/job/oUFFffwd?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oJkrgfwu?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kwalee/job/oUTQefwB?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oyR8ffww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/hkstrategies/job/o9nSffwn?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/ojdKffwf?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/oydvffwf?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/oNVzffwg?__jvst=job+board/',
'https://jobs.jobvite.com/careers/atirestoration/job/onX5efwn?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/oiO4efw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/opObgfwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oKsXffw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/atirestoration/job/oQnWdfw6?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/owfEgfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oBebgfw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/edobest/job/opgoffw2?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/rightpoint/job/oZWTdfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/lazparking/job/o99bgfwt?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oQmgffwr?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oYfFgfwS?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oieQffwl?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/ouHEgfwP?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oo6Fffw8?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/o0a4ffwd?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/von/job/osMIffwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gatewaycasinos/job/ojjwgfw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/imprivata/jobs?error=404&nl=1/',
'https://jobs.jobvite.com/careers/splunk/job/o3GGffwo?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/citco/job/oOAKffw7?__jvst=job+board&/',
'https://jobs.jobvite.com/careers/rightpoint/job/oCoygfwy?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/oKAnffwG?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/trustwave/job/okU3ffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/ojfuffw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/splunk/job/okLLffwP?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oBMkffwG?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/guidepoint-security/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/baymark/job/oJ1gffwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/yodlee/job/oJAEgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/xylem/job/ocSTffwW?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/biomarin/job/o2WUffwR?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oqLlgfww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/infoblox/job/ouvTffwR?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/siriusxm/job/os4Sefwm?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/o9Nagfw6?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/splunk/job/o19HffwQ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/ouGCffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/baymark/job/oawgffwV?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/siriusxm/job/o7a8ffwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/yodlee/job/osKdgfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oXUygfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/panasonic/job/o6Sbffw8?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/martinmarietta/job/odAFgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oePzgfwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/biomarin/job/obHRffwI?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/okMzgfwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oxTzffwY?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o8olgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oVZSffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dotdash/job/o5Vfffwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oo8lgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oT8rgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oge7efwz?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/yodlee/job/oONjgfwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o3ZFgfwH?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o4Wuffwt?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/fieldcore/job/onoHffwr?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/mediacom/job/oEJPefwa?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oQzFgfw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/wavemaker/job/ovUCefwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/oh6mgfwJ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/aspirepublicschools/job/oEwKffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/oZbKffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/oC22efwE?__jvst=job+board/',
'https://jobs.jobvite.com/careers/aspirepublicschools/job/otysffws?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/miniclip/job/o1zygfw8?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/o8yfgfwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/ouFBffwJ?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/oSlEffwQ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/macallistermachinery/job/oncHffwf?__jvst=career+site/',
'https://jobs.jobvite.com/careers/chevo-consulting/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oC9WffwG?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oCk0ffwV?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/omqIefws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oxB7efwd?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/o3x3ffwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/lewispr/job/oG2Cgfwk?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oZLygfwi?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/info-stretch-corporation/job/oqrigfw9/',
'https://jobs.jobvite.com/careers/yodlee/job/oQ4Egfwy?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/owo8ffw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/totalwine/job/oMu9gfwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/biomarin/job/oQI0cfwu?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/cmpa/job/oEAxgfwL?__jvst=Job+Board/',
'http://jobs.jobvite.com/careers/rlb/jobs?__jvst=RLB%20Website/',
'https://jobs.jobvite.com/careers/kathmandu/job/olokffw2?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/o2frgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oCTOefwh?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/oDvkgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/obKggfwb?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/o8kmffwN?__jvst=job+board/',
'https://jobs.jobvite.com/careers/rightpoint/job/ok1wgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oqLxgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oqhO8fwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oS8VffwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dentwizard/job/om2zgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oaP1ffwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oLhugfww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oiXVffw9?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/siriusxm/job/oPLxgfw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oM9ZffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o8zUffwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oQ9ygfwx?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qlik/job/oBRBffw2?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/trustwave/job/opZPffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/seco-energy/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/enterey/job/oJFKgfw8?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oqoDgfwr?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rtbhouse/job/oaaYefwg?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oryBgfwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/incontact/job/ofgoffwS?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/oBXxffw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oPPPffws?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/wavemaker/job/osl1efwM?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/dealcloud/jobs?__jvst=Intapp+Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oytrefwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oU4wgfwu?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/pilgrims/job/ouyPffwQ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/biomarin/job/oW3BgfwA?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/tngretail/job/of2egfwv?__jvst=career+site/',
'https://jobs.jobvite.com/careers/salsa/job/onaIgfwf?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/o9Qbgfwa?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/opVAgfwU?__jvst=job+board/',
'https://jobs.jobvite.com/careers/torrid/job/ofEX8fwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oNn5ffwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/oxtpffwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/internetbrands/job/otDbffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/atirestoration/job/oAQfffwE?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/pitchbook/job/oOlxffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/o0ivgfwN?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/o6Kxgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oF1Sffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/tivo/job/onBmffwj?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oxgeffw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/infoblox/job/ox0sgfwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/ol4kgfwJ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tivo/job/o8SGffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/hkstrategies/job/o4J2ffwO?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/kathmandu/job/onZAgfwW?__jvst=job+board/',
'https://jobs.jobvite.com/careers/qualys/job/oGqFgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/oJ6qffwe?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/oFdKgfwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/perrigocareers/job/ojP5ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/ovsPffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/customink/job/oO6ngfwh?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/service/redirect?c=qqq9VfwE&k=Jobs&j=o4kj4fwv&__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oqMcffwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oO80ffwV?__jvst=career+site/',
'https://jobs.jobvite.com/careers/ccaglobalpartners/job/ol3tgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/opzqgfwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/chiefind/job/oCSPffwi?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/oqabgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/o3vO8fwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/von/job/o7v2ffwD?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/benihana/job/osgFgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/oqEmffwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/centurycommunities/job/oiADgfwv?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oLRNffwo?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/omoO8fwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oCL0ffwm?__jvst=career+site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oHtOffwX?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/torrid/job/ofYP8fwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/ohFCffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/canadacartage/job/oAXXffwt?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/nakisa/job/oA0Pffwo?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/argusmedia/job/oVtEffw1?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/obArgfwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/macapartments/jobs?__jvst=JobBoard&__jvsd=Indeed/',
'https://jobs.jobvite.com/careers/benefitfocus/job/oxwXffwZ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/sbmmanagement/job/omMEgfwM?__jvst=career+site/',
'https://jobs.jobvite.com/careers/rehmann/job/ozB7ffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/shutterfly/job/oRDkdfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/herbalifenl/jobs?__jvst=Career%20Site/',
'https://jobs.jobvite.com/careers/hhglobal/job/opLBffwK?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/olhpgfw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oARO8fw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qualys/job/oTd7ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oTPlgfw3?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/oJqO8fwP?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=404/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=301/',
'https://jobs.jobvite.com/careers/carfax/p/main/',
'https://jobs.jobvite.com/careers/wri/jobs?error=301/',
'https://jobs.jobvite.com/careers/wilsonart/jobs?error=404/',
'https://jobs.jobvite.com/careers/cnoinc/jobs?error=301/',
'https://jobs.jobvite.com/careers/evergreenhealth/jobs?error=301/',
'https://jobs.jobvite.com/careers/gpc/job/o2frgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oCTOefwh?__jvst=career+site/',
'https://jobs.jobvite.com/careers/gpc/job/oDvkgfws?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/obKggfwb?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/citco/job/o8kmffwN?__jvst=job+board/',
'https://jobs.jobvite.com/careers/rightpoint/job/ok1wgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oqLxgfwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oqhO8fwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oS8VffwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dentwizard/job/om2zgfwX?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oaP1ffwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oLhugfww?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oiXVffw9?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/siriusxm/job/oPLxgfw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oM9ZffwT?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/o8zUffwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oQ9ygfwx?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qlik/job/oBRBffw2?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/trustwave/job/opZPffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/seco-energy/jobs?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/enterey/job/oJFKgfw8?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oqoDgfwr?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rtbhouse/job/oaaYefwg?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/gpc/job/oryBgfwA?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/incontact/job/ofgoffwS?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/oBXxffw4?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oPPPffws?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/wavemaker/job/osl1efwM?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/dealcloud/jobs?__jvst=Intapp+Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oytrefwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/oU4wgfwu?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/pilgrims/job/ouyPffwQ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/biomarin/job/oW3BgfwA?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/tngretail/job/of2egfwv?__jvst=career+site/',
'https://jobs.jobvite.com/careers/salsa/job/onaIgfwf?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/panasonic/job/o9Qbgfwa?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/opVAgfwU?__jvst=job+board/',
'https://jobs.jobvite.com/careers/torrid/job/ofEX8fwI?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oNn5ffwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/oxtpffwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/internetbrands/job/otDbffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/atirestoration/job/oAQfffwE?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/pitchbook/job/oOlxffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/o0ivgfwN?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/o6Kxgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oF1Sffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/tivo/job/onBmffwj?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/rightpoint/job/oxgeffw0?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/infoblox/job/ox0sgfwZ?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/ol4kgfwJ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tivo/job/o8SGffwF?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/hkstrategies/job/o4J2ffwO?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/kathmandu/job/onZAgfwW?__jvst=job+board/',
'https://jobs.jobvite.com/careers/qualys/job/oGqFgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/kathmandu/job/oJ6qffwe?__jvst=job+board/',
'https://jobs.jobvite.com/careers/gpc/job/oFdKgfwC?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/perrigocareers/job/ojP5ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/gpc/job/ovsPffwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/customink/job/oO6ngfwh?__jvst=Career+Site/',
'http://jobs.jobvite.com/careers/service/redirect?c=qqq9VfwE&k=Jobs&j=o4kj4fwv&__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/logitech/job/oqMcffwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oO80ffwV?__jvst=career+site/',
'https://jobs.jobvite.com/careers/ccaglobalpartners/job/ol3tgfwR?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/accentcare/job/opzqgfwo?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/chiefind/job/oCSPffwi?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/totalwine/job/oqabgfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/o3vO8fwe?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/von/job/o7v2ffwD?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/benihana/job/osgFgfwn?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/oqEmffwp?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/centurycommunities/job/oiADgfwv?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/evergreenhealth/job/oLRNffwo?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/omoO8fwq?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oCL0ffwm?__jvst=career+site/',
'https://jobs.jobvite.com/careers/cristaministries/job/oHtOffwX?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/torrid/job/ofYP8fwU?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/ohFCffwx?__jvst=career+site/',
'https://jobs.jobvite.com/careers/canadacartage/job/oAXXffwt?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/nakisa/job/oA0Pffwo?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/argusmedia/job/oVtEffw1?__jvst=Job+Board/',
'https://jobs.jobvite.com/careers/martinmarietta/job/obArgfwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/macapartments/jobs?__jvst=JobBoard&__jvsd=Indeed/',
'https://jobs.jobvite.com/careers/benefitfocus/job/oxwXffwZ?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/sbmmanagement/job/omMEgfwM?__jvst=career+site/',
'https://jobs.jobvite.com/careers/rehmann/job/ozB7ffwg?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/shutterfly/job/oRDkdfwL?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/herbalifenl/jobs?__jvst=Career%20Site/',
'https://jobs.jobvite.com/careers/hhglobal/job/opLBffwK?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/dominionenterprises/job/olhpgfw1?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/torrid/job/oARO8fw7?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/qualys/job/oTd7ffwc?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/tngretail/job/oTPlgfw3?__jvst=career+site/',
'https://jobs.jobvite.com/careers/torrid/job/oJqO8fwP?__jvst=Career+Site/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=404/',
'https://jobs.jobvite.com/careers/victaulic/jobs?error=301/',
'https://jobs.jobvite.com/careers/carfax/p/main/',
'https://jobs.jobvite.com/careers/wri/jobs?error=301/',
'https://jobs.jobvite.com/careers/wilsonart/jobs?error=404/',
'https://jobs.jobvite.com/careers/cnoinc/jobs?error=301/',
'https://jobs.jobvite.com/careers/evergreenhealth/jobs?error=301/',

]

w = []
added = set()
for i in duck:
    # print(i)
    word = re.findall(www, i)
    # word = re.findall(r"https://boards.greenhouse.io/(.*?)/", i)
    print(word)
    if word:
        w.append(*word)
        

for c in w:
    d = c.lower()
    if d not in text and d not in added and d != "j":
        a = open(words, "a")
        a.write(f"{c}\n")
        a.close()
        added.add(d)
    

# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"}

# bypassRecaptcha = "http://webcache.googleusercontent.com/search?q=cache:"

# page = 0

# while page < 1:
#     print("Page", page+1)

#     url = f"https://www.google.com/search?q=site:jobs.lever.co&ei=7nbjYMK6INLb-gTbx4HQBA&start={page}&sa=N&ved=2ahUKEwjC6YSs7czxAhXSrZ4KHdtjAEoQ8tMDegQIARA3&biw=1680&bih=461"

#     browser.get(url)
            
#     wait.until(EC.presence_of_element_located((By.XPATH, "//*[@id='pnnext']")))
#             # time.sleep(10)
#     # if wait.until(EC.presence_of_element_located((By.XPATH, "//*[@id='pnnext']"))):
#     response = browser.find_element_by_xpath("//*").get_attribute("outerHTML")
    
#     # time.sleep(5)
#     # response = requests.get(url, headers=headers)

#     # if response.ok:
#     soup = BeautifulSoup(response, "lxml")
#     href = soup.find_all("a", href=re.compile(link))
#     # print(href)
#     companies = []
#     added = set()

#     for h in href:
#         r = h["href"]
#         print(r)
#         word = re.findall(www, r)
#         if word: 
#             print("word", word)
#             companies.append(*word)

#     for c in companies:
#         d = c.lower()
#         if d not in text and d not in added and d != "j":
#             a = open(words, "a")
#             a.write(f"{d}\n")
#             a.close()
#             added.add(d)

#             if len(companies) < 1:
#                 break

#         companies = []

#     time.sleep(10)
#     page += 1
    

sys.exit(0)